deployment:
  nodePort:
    name: rest-api
    port: 30001
  replicaCount: 3
  image:
    name: hristo12319/todo_rest_api
    pullPolicy: IfNotPresent

  pods:
    name: todo-rest-api-pod
    metadata:
      labels:
        app: todo-rest-api-pod
        kind: backend

  probes:
    - name: readinessProbe
      url: /api/readyz
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
    - name: livenessProbe
      url: /api/healthz
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3

  secrets:
    dbSecrets: "db-secrets"
    oauthSecrets: "oauth-secrets"
    jwtSecret: "jwt-secret"

  configMaps:
    log: "log-config-map"
    rest: "rest-config-map"
    db: "db-config-map"
    activities: "activity-config-map"


