apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.nodePort.name }}
  namespace: {{ .Release.Namespace }}

spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.graphql.service.port }}
      targetPort: {{ .Values.global.graphql.service.port }}
      nodePort: {{ .Values.deployment.nodePort.port }}
  selector:
    {{ include "graphql-pod-labels" . | nindent 4 }}