apiVersion: v1
kind: Service
metadata:
  name: graphql-service

spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.graphql.service.port }}
      targetPort: {{ .Values.global.graphql.service.port }}
      nodePort: {{ .Values.deployment.nodePort }}
  selector:
    {{ include "graphql-pod-labels" . | nindent 4 }}