deployment:
  nodePort:
    port: 30008
    name: graphql-service
  replicaCount: 3
  pods:
    metadata:
      name: todo-graphql-api
      labels:
        app: todo-graphql-api
        kind: backend
  image:
    name: hristo12319/todo-graphql-api:1.0.4
    imagePullPolicy: IfNotPresent

  containers:
    name: todo-graphql-api-container

  initContainers:
    name: rest-api-waiter-container

  initContainerImage:
    name: curlimages/curl:8.8.0
    imagePullPolicy: IfNotPresent

  secrets:
    dbSecrets: "db-secrets"
    oauthSecrets: "oauth-secrets"
    jwtSecret: "jwt-secret"

  configMaps:
    log: "log-config-map"
    rest: "rest-config-map"
    db: "db-config-map"
    activities: "activity-config-map"

  probes:
    - name: readinessProbe
      url: /api/readyz
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 4
    - name: livenessProbe
      url: /api/healthz
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 4

