apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  backoffLimit: 4
  template:
    metadata:
      name: migration-pod
    spec:
      containers:
        - name: migration-container
          image: hristo12319/todo_api_migrations
          envFrom:
            - configMapRef:
                name: db-config-map
            - secretRef:
                name: db-secrets

      restartPolicy: Never
