apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deployment
  labels:
    app: rest-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-rest-api
      kind: backend
  template:
    metadata:
      name: todo-rest-container
      labels:
        app: todo-rest-api
        kind: backend
    spec:
      containers:
        - name: todo-rest-container
          image: hristo12319/todo_rest_api
          ports:
            - containerPort: 3434
          readinessProbe:
            httpGet:
              port: 3434
              path: /api/readyz
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 3434
              path: /api/healthz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          envFrom:
            - secretRef:
                name: db-secrets
            - secretRef:
                name: oauth-secrets
            - secretRef:
                name: jwt-secret
            - configMapRef:
                name: log-config-map
            - configMapRef:
                name: rest-config-map
            - configMapRef:
                name: db-config-map
