apiVersion: v1
kind: Service
metadata:
  name: rest-api

spec:
  type: NodePort
  ports:
    - port: 3434
      targetPort: 3434
      nodePort: 30001
  selector:
    app: todo-rest-api
    kind: backend