apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
  namespace: {{ .Release.Namespace }}

stringData:
  CLIENT_ID: "{{ .Values.global.oauthSecrets.clientId }}"
  CLIENT_SECRET: "{{ .Values.global.oauthSecrets.clientSecret }}"
  CALLBACK_URL: "{{ .Values.global.oauthSecrets.callbackUrl }}"