apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets

stringData:
  CLIENT_ID: "{{ .Values.global.oauth.clientId }}"
  CLIENT_SECRET: "{{ .Values.global.oauth.clientSecret }}"
  CALLBACK_URL: "{{ .Values.global.oauth.callbackUrl }}"