apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets

stringData:
  CLIENT_ID: "Ov23lir9dNQ9jHS7oTcP"
  CLIENT_SECRET: "6c2504afd07f887af871a3ac02bd556a86e0e0b9"
  CALLBACK_URL: "http://localhost:30001/auth2/callback"