apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulSet.headlessServiceName }}
  namespace: {{ .Release.Namespace }}

spec:
  clusterIP: None
  selector:
    {{- include "postgres-pod-labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.global.postgres.service.port }}