apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Release.Namespace }}

stringData:
  POSTGRES_USER: "{{ .Values.global.postgresSecrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.global.postgresSecrets.POSTGRES_PASSWORD }}"