apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulSet.clusterIpService.clusterIpName }}
  labels:
    {{- include "postgres-pod-labels" . | nindent 4 }}

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.statefulSet.clusterIpService.servicePort }}
      targetPort: {{ .Values.global.postgres.service.port }}
  selector:
    {{- include "postgres-pod-labels" . | nindent 4 }}