apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful-set

spec:
  serviceName: db-headless
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db-pod
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          envFrom:
            - configMapRef:
                name: db-config-map
            - secretRef:
                name: db-secrets
  volumeClaimTemplates:
    - metadata:
        name: postgresdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi




