global:
  activities:
    url: https://bored-api.appbrewery.com/random
  rest:
    service:
      port: 3434
      url: http://rest-api:3434

  graphql:
    service:
      port: 8090
  postgres:
    service:
      name: mydatabase
      port: 5432

  jwtSecrets:
    jwtKey: dummy jwt secret

  logConfigMap:
    appLogLevel: info
    appLogFormat: json

  oauthSecrets:
    clientId: dummy clientId
    clientSecret: dummy client secret
    callbackUrl: dummy callback url

  postgresSecrets:
    POSTGRES_USER: dummy user
    POSTGRES_PASSWORD: dummy password

  gateway:
    istio: ingressgateway
    name: ingress-gateway-configuration
    tls:
      mode: MUTUAL
      credentialName: api-mtls-cred
    hosts:
      name: api.local.test
    port:
      number: 443
      protocol: HTTPS
      name: https-mtls

  mtls:
    mode: STRICT
