global:
  activities:
    url: https://bored-api.appbrewery.com/random
  rest:
    service:
      port: 3434
      url: http://rest-api:3434

  graphql:
    service:
      port: 8090
  postgres:
    service:
      name: mydatabase
      port: 5432

  jwt:
    jwtKeySecret: dummy jwt secret

  log:
    appLogLevel: info
    appLogFormat: json

  oauth:
    clientId: dummy clientId
    clientSecret: dummy client secret
    callbackUrl: dummy callback url
