apiVersion: v1
kind: Service
metadata:
  name: graphql-service

spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30008
  selector:
    app: todo-graphql-api
    kind: backend