apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-graphql-api
      kind: backend
  template:
    metadata:
      name: todo-graphql-api
      labels:
        app: todo-graphql-api
        kind: backend
    spec:
      initContainers:
        - name: rest-api-waiter-container
          image: curlimages/curl:8.8.0
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              set -e
              until curl -sf http://rest-api:3434/api/healthz ; do
                sleep 2
              done
              until curl -sf http://rest-api:3434/api/readyz ; do
                sleep 2
              done
              echo "Todo Rest Api is ready"
      containers:
        - name: todo-graphql-api-container
          image: hristo12319/todo_graphql_api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - secretRef:
                name: db-secrets
            - secretRef:
                name: oauth-secrets
            - secretRef:
                name: jwt-secret
            - configMapRef:
                name: log-config-map
            - configMapRef:
                name: rest-config-map
            - configMapRef:
               name: db-config-map
